config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :projects, except: [:destroy] do
    resources :tasks, except: [:destroy]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'projects#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord
  # validations
  validates :name, presence: true, uniqueness: true

  # associations
  has_many :projects_users
  has_many :tasks
  has_many :users, through: :projects_users

  accepts_nested_attributes_for :projects_users

  def owner
    projects_users.find_by(role: :owner).user
  end
end

app/models/projects_user.rb
# frozen_string_literal: true

class ProjectsUser < ApplicationRecord
  enum role: %i[collaborator owner]

  # associations
  belongs_to :project
  belongs_to :user
end

app/models/task.rb
# frozen_string_literal: true

class Task < ApplicationRecord
  # associatons
  belongs_to :project
  belongs_to :creator, class_name: 'User', foreign_key: 'creator_id'
  belongs_to :assignee, class_name: 'User', foreign_key: 'assignee_id', optional: true

  enum status: %i[to_do in_progress done]

  # validations
  validates :name, presence: true

  # delegates
  delegate :name, to: :creator, prefix: true
  delegate :name, to: :assignee, prefix: true, allow_nil: true
  delegate :name, to: :project, prefix: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # validations
  validates :name, presence: true

  # associations
  has_many :projects_users
  has_many :projects, through: :projects_users
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, only: %i[show edit update destroy]
  before_action :set_users, only: %i[new edit]

  # GET /projects or /projects.json
  def index
    @projects = current_user.projects
  end

  # GET /projects/1 or /projects/1.json
  def show; end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit; end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params.merge(projects_users_attributes: [{ user_id: current_user.id,
                                                                              role: :owner }]))

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_project
    @project = Project.find(params[:id])
  end

  def set_users
    @users = User.where.not(id: current_user.id)
  end

  # Only allow a list of trusted parameters through.
  def project_params
    params.require(:project).permit(:name, user_ids: [])
  end
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

class TasksController < ApplicationController
  before_action :set_project
  before_action :set_task, only: %i[show edit update destroy]

  # GET /tasks or /tasks.json
  def index
    @tasks = @project.tasks
  end

  # GET /tasks/1 or /tasks/1.json
  def show; end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit; end

  # POST /tasks or /tasks.json
  def create
    @task = @project.tasks.new(task_params.merge(creator: current_user))

    respond_to do |format|
      if @task.save
        format.html { redirect_to project_task_path(@project, @task), notice: 'Task was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to project_task_path(@task), notice: 'Task was successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_project
    @project = Project.find(params[:project_id])
  end

  def set_task
    @task = Task.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def task_params
    params.require(:task).permit(:name, :description, :assignee_id, :status)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/projects_helper.rb
# frozen_string_literal: true

module ProjectsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      | Whitebox
    %meta{ name: "viewport", content: "width=device-width,initial-scale=1" }
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  %body
    %link{href: "https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css", rel: "stylesheet" }
    .container
      - if user_signed_in?
        = link_to 'Home', root_path
        %br
        = button_to "sign out", destroy_user_session_path, method: :delete, data: { turbo: false }, class: 'btn btn-link'
      = yield

app/views/projects/_form.html.haml
= form_with(model: project) do |form|
  - if project.errors.any?
    %div{:style => "color: red"}
      %h2
        = pluralize(project.errors.count, "error")
        prohibited this project from being saved:
      %ul
        - project.errors.each do |error|
          %li= error.full_message
  %div
    = form.label :name, style: "display: block"
    = form.text_field :name
  %div
    = form.label :collaborators, style: "display: block"
    = form.select :user_ids, options_from_collection_for_select(@users || [], :id, :email, project.user_ids), {}, multiple: true
  %div
    = form.submit

app/views/projects/_project.html.haml
%div{:id => "#{dom_id project}"}
  %p
    %strong Name:
    = project.name

app/views/projects/edit.html.haml
%h1 Editing project
= render "form", project: @project
%br/
%div
  = link_to "Show this project", @project
  |
  \#{link_to "Back to projects", projects_path}

app/views/projects/index.html.haml
%p{:style => "color: green"}= notice
%h1 My Projects
.row.flex-lg-nowrap
  .col.mb-3
    .e-panel.card
      .card-body
        .e-table
          .table-responsive.table-lg.mt-3
            %table.table.table-bordered
              %thead
                %tr
                  %th Name
                  %th Tasks
                  %th Actions

              %tbody
                - @projects.each do |project|
                  %tr
                    %td.text-nowrap.align-middle
                      %span
                      = project.name
                    %td.text-nowrap.align-middle
                      %span
                      = link_to "View Tasks", project_tasks_path(project)
                    %td.text-center.align-middle
                      .btn-group.align-top
                        %button{ type: "button", "data-toggle": "modal", "data-target": "#user-form-modal" }
                          = link_to 'Edit', edit_project_path(project)
                        = button_to project, method: :delete, form: { data: { turbo_confirm: 'Are you sure?' } } do
                          %i.fa.fa-eye

= link_to "New project", new_project_path

app/views/projects/new.html.haml
%h1 New project
= render "form", project: @project
%br/
%div
  = link_to "Back to projects", projects_path

app/views/projects/show.html.haml
%p{:style => "color: green"}= notice
= render @project
%div
  = link_to "Edit this project", edit_project_path(@project)
  |
  \#{link_to "Back to projects", projects_path}

app/views/tasks/_form.html.haml
- path = @task.persisted? ? project_task_path(@project, @task) : project_tasks_path(@project)
= form_for @task, url: path do |f|
  - if @task.errors.any?
    #error_explanation
      %h2= "#{pluralize(@task.errors.count, "error")} prohibited this task from being saved:"
      %ul
        - @task.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_field :description
  - if @task.persisted?
    .field
      = f.label :status
      = f.select :status, Task.statuses.keys.map { |s| [s.humanize, s] }
  .field
    = f.label :assignee
    = f.select :assignee_id, options_from_collection_for_select(@project.users, :id, :email, @task.assignee_id), include_blank: true
  .actions
    = f.submit 'Save'

app/views/tasks/edit.html.haml
%h1 Editing task

= render 'form'

= link_to 'Show', project_task_path(@project, @task)
\|
= link_to 'Back', project_tasks_path(@project)

app/views/tasks/index.html.haml
%p{ style: "color: green" }
  = notice
%h1 Listing tasks
.row.flex-lg-nowrap
  .col.mb-3
    .e-panel.card
      .card-body
        .e-table
          .table-responsive.table-lg.mt-3
            %table.table.table-bordered
              %thead
                %tr
                  %th Name
                  %th Project
                  %th Creator
                  %th Assignee
                  %th Status
                  %th Actions
              %tbody
                - @tasks.each do |task|
                  %tr
                    %td.text-nowrap.align-middle
                      %span
                        = task.name
                    %td.text-nowrap.align-middle
                      %span
                        = task.project_name
                    %td.text-nowrap.align-middle
                      %span
                        = task.creator_name
                    %td.text-nowrap.align-middle
                      %span
                        = task.assignee_name
                    %td.text-nowrap.align-middle
                      %span
                        = task.status.humanize
                    %td.text-center.align-middle
                      .btn-group.align-top
                        %button{ type: "button", "data-toggle": "modal", "data-target": "#user-form-modal" }
                          = link_to 'Edit', edit_project_task_path(@project, task)
                        = button_to project_task_path(@project, task), method: :get do
                          %i.fa.fa-eye

%br

= link_to 'New Task', new_project_task_path(@project)

app/views/tasks/new.html.haml
%h1 New task

= render 'form'

= link_to 'Back', project_tasks_path(@project)

app/views/tasks/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @task.name
%p
  %b Project:
  = @task.project_name
%p
  %b Creator:
  = @task.creator_name
%p
  %b Assignee:
  = @task.assignee_name
%p
  %b Status:
  = @task.status.humanize
%p
  %b Description:
  = @task.description

= link_to 'Edit', edit_project_task_path(@project, @task)
\|
= link_to 'Back', project_tasks_path(@project)